### PR TITLE
Remove invalid navbar item type

### PR DESCRIPTION
**Pull request by skoech**
Navbar item `type: dropdown` is invalid.

Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

### CODE REVIEW

**Review by Licenser — CHANGES_REQUESTED** [review]
This isn't a invalid type, it just needs a local clean of the cache :)

**Review by darach — APPROVED** [review]
LGTM 👍

**Comment by Licenser** [comment]
This is how it looks: 
grafik

**Comment by skoech** [comment]
Just cleaned the cache, and it worked like a charm. Thanks, y'all. :)
I'll close this PR now.

**Pull request closed without merging**
