### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by sandipb**
Mostly spelling, some formatting fixes.

For filter recipe, I thought the passthrough command was not relevant, but the contents of the inputs was more relevant as it shows the effect of filtering.

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
Great contribution! We left those typos just for you, and you found them all! :rocket:

**Comment by mfelsche** [comment]
Those changes will be lost when we switch to 0.12. Would you mind replicating those changes to the versioned_docs/0.11 folder?

**Comment by sandipb** [comment]
> Those changes will be lost when we switch to 0.12. Would you mind replicating those changes to the versioned_docs/0.11 folder?

@mfelsche Done

**Review by mfelsche — APPROVED** [review]

**Comment by mfelsche** [comment]
Thx! You will be forever in our hearts, @sandipb ! :heart:

**Pull request merged**
