### PR TITLE
2022 april tremors to mob

### PR DESCRIPTION
**Pull request by GaryPWhite**

### CODE REVIEW

**Comment by GaryPWhite** [comment]
merging fer per request from @Licenser https://github.com/tremor-rs/tremor-www/pull/174

**Comment by GaryPWhite** [comment]
resolving some conflicts...

**Comment by Licenser** [comment]
Woooh woooh ! Thank you !!!

**Review by Licenser — APPROVED** [review]

**Comment by Licenser** [comment]
It looks like there are some merge conflicts with the branch :(

**Comment by GaryPWhite** [comment]
rebased manually 🤞

**Pull request merged**
