### PR TITLE
2022 april tremors

### PR DESCRIPTION
**Pull request by GaryPWhite**
Hey Tremor party people!

As promised, here's a breakdown and editorial on some of the changes we've seen in the last month. I'm more than happy to edit, dive into, change any of this as we see fit to make sure we cover important bits appropriately. Let me know what you think!

I've dated this for the second working day in May, I'm aiming to publish these on a cadence like that moving forward.

### CODE REVIEW

**Comment by Licenser** [comment]
First of all thanks for that lovely post!

This is a bit of a tricky one, we're somewhat stuck with `main` on RC.1 with new code gernation and www still on 0.11 with old code generation. I'm not 100% sure how to best resolve this conflict without doing a ton of changes to the current `main` on -www, the best idea I have would be targeting this at the `mob-v12-refresh` and then merging it together with that branch.

What do you think?

**Comment by GaryPWhite** [comment]
no problem at all. sec!

**Comment by GaryPWhite** [comment]
so just to be clear I now have two branches targeted for merging. This PR and [this PR](https://github.com/tremor-rs/tremor-www/pull/176) I think that's what you wanted but let me know if I missed a trick

**Comment by Licenser** [comment]
Heya, sorry ja release time is all a bit chaotic, sorry, with #176 this can be closed, we'll merge the changes over there :)

**Pull request closed without merging**
